name: push

on: 
  push:
    branches: [ main ]
  workflow_dispatch:
  pull_request:
    types: [labeled,opened,edited]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        if: github.event_name == 'pull_request' && github.event.pull_request.title == '[ImgBot] Optimize images'
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_FORKS: "false"
          MERGE_RETRIES: "2"
          MERGE_RETRY_SLEEP: "10000"
          UPDATE_METHOD: "rebase"
  build:
    needs: automerge
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Dispatcher
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          token: ${{ secrets.TOKEN }}
          repo: A-JiuA/Hexo
          workflow: build.yml